=== xsf/xeps/inbox/xep.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--

Copyright (c) 1999 - 2010 XMPP Standards Foundation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

-->

<!ELEMENT xep ( header, section1* ) >
<!ATTLIST xep
          xmlns CDATA '' >
<!ELEMENT header ( title, abstract, legal, number, status, lastcall*, interim*, type, sig, approver*, dependencies, supersedes, supersededby, shortname, schemaloc*, registry?, discuss?, expires?, author+, revision+, councilnote? ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT abstract (#PCDATA)* >
<!ELEMENT legal ( copyright, permissions, warranty, liability, conformance ) >
<!ELEMENT copyright (#PCDATA | link)* >
<!ELEMENT permissions (#PCDATA | link)* >
<!ELEMENT warranty (#PCDATA | link)* >
<!ELEMENT liability (#PCDATA | link)* >
<!ELEMENT conformance (#PCDATA | link)* >
<!ELEMENT number (#PCDATA)* >
<!ELEMENT status (#PCDATA)* >
<!ELEMENT lastcall (#PCDATA)* >
<!ELEMENT interim EMPTY>
<!ELEMENT type (#PCDATA)* >
<!ELEMENT sig (#PCDATA)* >
<!ELEMENT approver (#PCDATA)* >
<!ELEMENT dependencies ( spec* ) >
<!ELEMENT supersedes ( spec? ) >
<!ELEMENT supersededby ( spec? ) >
<!ELEMENT spec (#PCDATA)* >
<!ELEMENT shortname (#PCDATA)* >
<!ELEMENT schemaloc ( ns?, url ) >
<!ELEMENT ns (#PCDATA)* >
<!ELEMENT url (#PCDATA)* >
<!ELEMENT registry EMPTY>
<!ELEMENT discuss (#PCDATA)* >
<!ELEMENT expires (#PCDATA)* >
<!ELEMENT author ( firstname, surname, authornote?, org?, email?, jid?, uri? ) >
<!ELEMENT firstname (#PCDATA)* >
<!ELEMENT surname (#PCDATA)* >
<!ELEMENT authornote EMPTY>
<!ELEMENT org (#PCDATA)* >
<!ELEMENT email (#PCDATA)* >
<!ELEMENT jid (#PCDATA)* >
<!ELEMENT uri (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark ( p | ul )* >
<!ELEMENT councilnote (#PCDATA)* >
<!ELEMENT section1 ( div | p | section2 | example | code | ul | ol | dl | table )* >
<!ATTLIST section1
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section2 ( div | p | section3 | example | code | ul | ol | dl | table )* >
<!ATTLIST section2
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section3 ( div | p | section4 | example | code | ul | ol | dl | table )* >
<!ATTLIST section3
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section4 ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST section4
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT div ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST div 
          class CDATA ''
          style CDATA '' >
<!ELEMENT p (#PCDATA | br | img | link | note | tt | dfn | em | strong | cite | span)* >
<!ATTLIST p 
          class CDATA ''
          style CDATA '' >
<!ELEMENT br EMPTY >
<!ELEMENT ul (li+) >
<!ATTLIST ul 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT ol (li+) >
<!ATTLIST ol 
          class CDATA '' 
          start CDATA '' 
          style CDATA '' >
<!ELEMENT li (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ATTLIST li 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT dl (di+) >
<!ELEMENT di ( dt, dd ) >
<!ELEMENT dt (#PCDATA)* >
<!ELEMENT dd (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA '' >
<!ELEMENT link (#PCDATA)* >
<!ATTLIST link url CDATA '' >
<!ELEMENT note (#PCDATA | link | tt | dfn | em | strong | cite | span)* >
<!ELEMENT example (#PCDATA)* >
<!ATTLIST example caption CDATA '' >
<!ELEMENT code (#PCDATA)* >
<!ATTLIST code caption CDATA '' >
<!ELEMENT table (tr)* >
<!ATTLIST table caption CDATA '' >
<!ELEMENT tr ( th | td )* >
<!ELEMENT th (#PCDATA)* >
<!ATTLIST th 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT td (#PCDATA)* >
<!ATTLIST td 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT tt (#PCDATA)* >
<!ELEMENT dfn (#PCDATA)* >
<!ELEMENT em (#PCDATA)* >
<!ELEMENT strong (#PCDATA)* >
<!ELEMENT cite (#PCDATA)* >
<!ELEMENT span (#PCDATA | link | tt | dfn | em | strong )* >
<!ATTLIST span 
          class CDATA ''
          style CDATA '' >

=== xsf/xeps/xep-0224.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Attention</title>
  <abstract>This document defines an XMPP protocol extension for getting the attention of another user.</abstract>
  &LEGALNOTICE;
  <number>0224</number>
  <status>Draft</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XMPP IM</spec>
    <spec>XEP-0030</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>attention</shortname>
  <schemaloc>
    <url>http://xmpp.org/schemas/attention.xsd</url>
  </schemaloc>
  <author>
    <firstname>Andreas</firstname>
    <surname>Monitzer</surname>
    <email>andy@monitzer.com</email>
    <jid>andy@monitzer.com</jid>
  </author>
  <revision>
    <version>1.0</version>
    <date>2008-11-13</date>
    <initials>psa</initials>
    <remark><p>Per a vote of the XMPP Council, advanced specification to Draft.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2008-10-01</date>
    <initials>psa</initials>
    <remark><p>Modified namespace to incorporate namespace versioning.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2007-08-08</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2007-07-03</date>
    <initials>am</initials>
    <remark><p>Initial version.</p></remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>Even though a client might be available (as stated in the most recent presence stanza), the user this client belongs to might not be focused on the client currently. &xep0132; defines a method for a physical test of user presence. Since this requires special hardware that cannot be assumed to be available, this XEP defines a software-only implementation where no direct feedback is expected. This feature is known as 'nudge' or 'buzz' in some non-XMPP IM protocols.</p>
  <p>It was discussed whether this feature belongs in &xep0085;. However, the semantics are inherently different, since Chat State Notifications describe the sender's state, not a request to change the receiver's. Thus, a separate extension is desirable.</p>
</section1>
<section1 topic='Requirements' anchor='reqs'>
  <p>The specification addresses remotely getting the user's attention in a more assertive way than simple text messages.</p>
</section1>
<section1 topic='Protocol' anchor='protocol'>
  <p>In the following conversation, a user talks to somebody, but this user doesn't respond. The second inquiry includes an attention extension.</p>
  <example caption="User sends a regular message"><![CDATA[
<message from='calvin@usrobots.lit/lab'
         to='herbie@usrobots.lit/home'
         type='chat'>
  <body>All right, then, Herbie, give! We're waiting.</body>
</message>
  ]]></example>
  <p>When no reply is received, the sending user might want to grab the other's attention. This is done by sending a message that includes an &lt;attention/&gt; element qualified by the 'urn:xmpp:attention:0' namespace &VNOTE;. Note: The message MAY include a &BODY; element.</p>
  <example caption="User tries to capture the other's attention"><![CDATA[
<message from='calvin@usrobots.lit/lab'
         to='herbie@usrobots.lit/home'
         type='headline'>
  <attention xmlns='urn:xmpp:attention:0'/>
  <body>Why don't you answer, Herbie?</body>
</message>
  ]]></example>
  <p>Finally, the receiving user notices the urgency of the message and responds.</p>
  <example caption="The user whose attention has been captured responds."><![CDATA[
<message from='herbie@usrobots.lit/home'
         to='calvin@usrobots.lit/lab'
         type='chat'>
  <body>I cannot. You know I cannot! Dr. Bogert and Dr. Lanning don't want me to.</body>
</message>
  ]]></example>
</section1>
<section1 topic='Business Rules' anchor='rules'>
  <p>The following rules apply to generating and processing of the attention extension.</p>
  <ol>
    <li>Before sending an attention message stanza, the client SHOULD confirm support for it in the other client as described under <link url='#disco'>Determining Support</link>.</li>
    <li>The message stanza containing the attention extension MAY contain a body and/or other extensions, which is to be displayed along with executing the attention event.</li>
    <li>In message stanzas containing either &xep0203; data, attention extensions MUST be ignored, since the attention request is an instant event which SHOULD NOT be replayed after a delay.</li>
    <li>Messages containing an attention extension SHOULD use the headline message type to avoid offline storage.</li>
    <li>The attention extension MUST NOT be sent in &IQ; stanzas, since use of this feature is part of a messaging conversation.</li>
  </ol>
</section1>
<section1 topic='Determining Support' anchor='disco'>
  <p>If an entity wishes to receive the attention extension, it MUST advertise that fact in its responses to &xep0030; information ("disco#info") requests by returning a feature of "urn:xmpp:attention:0":</p>
  <example caption='A disco#info query'><![CDATA[
<iq type='get'
    from='calvin@usrobots.lit/lab'
    to='herbie@usrobots.lit/home'
    id='disco1'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
  ]]></example>
  <example caption='A disco#info response'><![CDATA[
<iq type='result'
    from='herbie@usrobots.lit/home'
    to='calvin@usrobots.lit/lab'
    id='disco1'>
  <query xmlns='http://jabber.org/protocol/disco#info'>
    <feature var='urn:xmpp:attention:0'/>
  </query>
</iq>
  ]]></example>
  <p>In order for an application to determine whether an entity supports this protocol, where possible it SHOULD use the dynamic, presence-based profile of service discovery defined in &xep0115;. However, if an application has not received entity capabilities information from an entity, it SHOULD use explicit service discovery instead.</p>
</section1>
<section1 topic='Implementation Notes' anchor='impl'>
  <p>The implementation of the alert is up to the developer. Possible behavior includes:</p>
  <ul>
    <li>Shaking the window.</li>
    <li>Playing a specific sound not used for any other event.</li>
    <li>Flashing the screen.</li>
    <li>Enabling external hardware such as flashing lights.</li>
    <li>Let it be user customizable.</li>
  </ul>
  <p>Because some users might not want this feature to disturb them, a client MUST either (1) allow the user to disable support or (2) disable the feature by default and process attention requests only if the user has explicitly enabled support. When the feature is disabled, it MUST NOT be advertised in disco#info.</p>
  <p>Rate-limiting might be desirable in some implementations.</p>
  <p>Formal feedback in response to the attention request to the requesting user is not specified, and so the request might be silently dropped.</p>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>It is RECOMMENDED that a client accept message stanzas containing the attention extension only contacts that are in the user's roster or with whom the user's client is currently sharing directed presence, mainly to prevent the user from being annoyed by attention requests from random entities on the network. A client could implement finer-grained control if desired (e.g., allow attention requests only from entities in a particular roster group).</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <section2 topic='Protocol Namespaces' anchor='registrar-ns'>
    <p>This specification defines the following XML namespace:</p>
    <ul>
      <li>urn:xmpp:attention:0</li>
    </ul>
    <p>The &REGISTRAR; includes this namespace in the registry located at &NAMESPACES;, as described in Section 4 of &xep0053;.</p>
  </section2>
  <section2 topic='Protocol Versioning' anchor='registrar-versioning'>
    &NSVER;
  </section2>
</section1>
<section1 topic='XML Schema' anchor='schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='urn:xmpp:attention:0'
    xmlns='urn:xmpp:attention:0'
    elementFormDefault='qualified'>

  <xs:annotation>
    <xs:documentation>
      The protocol documented by this schema is defined in
      XEP-0224: http://www.xmpp.org/extensions/xep-0224.html
    </xs:documentation>
  </xs:annotation>

  <xs:element name='attention' type='empty'/>

  <xs:simpleType name='empty'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value=''/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
  ]]></code>
</section1>
<section1 topic='Acknowledgements' anchor='ack'>
  <p>The quotes have been taken from Isaac Asimov's short story "Liar!" as published in the book <cite>The Complete Robot</cite>.</p>
</section1>
</xep>

=== xsf/xeps/xep-template.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>XEP Template</title>
  <abstract>This specification provides an example of the format for XMPP Extension Protocols (XEPs).</abstract>
  &LEGALNOTICE;
  <number>xxxx</number>
  <status>ProtoXEP</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XEP-0001</spec>
    <spec>Etc.</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>NOT_YET_ASSIGNED</shortname>
  <tags>
    <tag>template</tag>
  </tags>
  <author>
    <firstname>Peter</firstname>
    <surname>Saint-Andre</surname>
    <email>stpeter@jabber.org</email>
    <jid>stpeter@jabber.org</jid>
  </author>
  <revision>
    <version>0.0.1</version>
    <date>2001-09-14</date>
    <initials>psa</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>This is a template for use in writing XMPP Extension Protocol specifications (XEPs). For detailed information about the XSF's standards process and how to write a XEP, refer to "XEP-0001: XMPP Extension Protocols" and "XEP-0143: Guidelines for Authors of XMPP Extension Protocols".</p>
</section1>
<section1 topic='Requirements' anchor='reqs'>
  <p>STRONGLY RECOMMENDED.</p>
</section1>
<section1 topic='Glossary' anchor='glossary'>
  <p>OPTIONAL.</p>
</section1>
<section1 topic='Use Cases' anchor='usecases'>
  <p>STRONGLY RECOMMENDED.</p>
</section1>
<section1 topic='Business Rules' anchor='rules'>
  <p>OPTIONAL.</p>
</section1>
<section1 topic='Implementation Notes' anchor='impl'>
  <p>OPTIONAL.</p>
</section1>
<section1 topic='Accessibility Considerations' anchor='access'>
  <p>REQUIRED.</p>
</section1>
<section1 topic='Internationalization Considerations' anchor='i18n'>
  <p>OPTIONAL.</p>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>REQUIRED.</p>
</section1>
<section1 topic='Privacy Considerations' anchor='privacy'>
  <p>REQUIRED.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>REQUIRED.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>REQUIRED.</p>
</section1>
<section1 topic='Design Considerations' anchor='design'>
  <!-- Use this section to describe other approaches which have been considered
  during the design of this protocol and why they have been rejected. Having
  the result and a summary of long or complicated discussions in the document
  itself instead of list or chat archives serves future readers. -->
  <p>RECOMMENDED.</p>
</section1>
<section1 topic='XEP Styling Examples (1st Level Heading)' anchor='styling'>
  <p>PLEASE REMOVE THIS SECTION. These are just examples for the RECOMMENDED ways to style your XEP.</p>
  <section2 topic='2nd Level Heading' anchor='styling-examples'>
    <p>This is regular XEP text. It can contain <strong>strong</strong> and <em>emphasized</em> markup as well as <tt>fixed-width text</tt>.</p>
    <p>This is text with a line break.<br/>New line.</p>
    <p>This is text with a footnote<note>This is the footnote.</note>.</p>
    <p>This is a <link url='#styling-examples'>link to a section in this document</link>.</p>
    <p>This is a reference to another XEP: &xep0001;, it can be re-referenced as <cite>XEP-0001</cite> later in the text.</p>
    <code caption='Code block caption'>Code block content.</code>
    <ol>
      <li>This is an ordered list. First item</li>
      <li>Second item</li>
    </ol>
    <ul>
      <li>This is an unordered list. First item</li>
      <li>Second item</li>
    </ul>
    <dl>
      <di>
        <dt>Definition List</dt>
        <dd>
          A definition list contains definition items with a title and a description.
        </dd>
      </di>
    </dl>
    <p class='box'>Note: This is an informational box</p>
    <example caption='Example of embedding XMPP XML'><![CDATA[
<iq from='hag66@shakespeare.lit/pda'
    id='h7ns81g'
    to='shakespeare.lit'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#items'/>
</iq>
]]></example>
    <cve id="2017-5589" url="https://rt-solutions.de/en/cve-2017-5589_xmpp_carbons/">Name of a CVE relevant to the XEP</cve>
    <cve id="2017-5589">Another CVE with no primary source</cve>
    <section3 topic='3rd Level Heading' anchor='syling-examples-3rd'>
      <p>Text in a Sub-Sub-Section.</p>
      <section4 topic='4th Level Heading' anchor='syling-examples-4th'>
        <p>Text in a Sub-Sub-Sub-Section.</p>
      </section4>
    </section3>
  </section2>
</section1>
<section1 topic='XML Schema' anchor='schema'>
  <p>REQUIRED for protocol specifications.</p>
</section1>
</xep>

=== xsf/xeps/xep-0063.xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM "xep.ent">
%ents;
]>

<?xml-stylesheet type='text/xsl' href='xep.xsl'?>

<xep>
<header>
  <title>Basic Filtering Operations</title>
  <abstract>A module that provides basic conditions and actions for packet filtering.</abstract>
  &LEGALNOTICE;
  <number>0063</number>
  <status>Deferred</status>
  <type>Informational</type>
  <sig>Standards</sig>
  <dependencies><spec>XEP-0062</spec></dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>Not yet assigned</shortname>
  <author>
    <firstname>Robert</firstname>
    <surname>Norris</surname>
    <email>rob@cataclysm.cx</email>
    <jid>rob@cataclysm.cx</jid>
  </author>
  <revision>
    <version>0.2</version>
    <date>2003-09-30</date>
    <initials>psa</initials>
    <remark>At the request of the author, changed the status of this document to Deferred pending development of an implementation; also changed the type to Informational.</remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2002-12-05</date>
    <initials>rn</initials>
    <remark>Initial version.</remark>
  </revision>
</header>

<section1 topic='Introduction'>
  <p>This document defines a module for &xep0062; that provides some basic conditions and actions to perform common packet filtering tasks.</p>

  <p>This module operates in the "http://jabber.org/protocol/filter/basic" namespace.</p>
</section1>

<section1 topic='Conditions'>
  <p>This module defines the fullowing conditions:</p>

  <ul>
    <li>&lt;message/> - true if the packet is a &lt;message/> packet.</li>
    <li>&lt;presence/> - true if the packet is a &lt;presence/> packet.</li>
    <li>&lt;iq/> - true if the packet is a &lt;iq/> packet. If this element contains CDATA, then it must match the namespace of the first element inside the packet (typically &lt;query/>) in order to be true.</li>
    <li>&lt;to/> - true when the CDATA of this element matches the "to" attribute of the packet.</li>
    <li>&lt;from/> - true when the CDATA of this element matches the "from" attribute of the packet.</li>
    <li>&lt;type/> - true when the CDATA of this element matches the "type" attribute of the packet.</li>
  </ul>

  <example caption='Matches all presence packets'><![CDATA[
<presence xmlns='http://jabber.org/protocol/filter/basic'/>
]]></example>

  <example caption='Matches all jabber:iq:version IQ packets'><![CDATA[
<iq xmlns='http://jabber.org/protocol/filter/basic'>jabber:iq:version</iq>
]]></example>

  <example caption='Matches all packets from user@company.com'><![CDATA[
<from xmlns='http://jabber.org/protocol/filter/basic'>user@company.com</from>
]]></example>

</section1>

<section1 topic='Actions'>
  <p>This module defines the fullowing actions:</p>

  <ul>
    <li>&lt;drop/> - drops the packet</li>
    <li>&lt;bounce/> - bounces the packet with the error specified in the "code" attribute of this element.</li>
    <li>&lt;redirect/> - redirects the packet to the JID specified in the CDATA of this element.</li>
    <li>&lt;copy/> - sends a copy of the packet to the JID specified in the CDATA of this element, while giving the original packet to the user.</li>
  </ul>

  <example caption='Pretend that we don&apos;t exist'><![CDATA[
<bounce xmlns='http://jabber.org/protocol/filter/basic' code='404'/>
]]></example>

  <example caption='Send a copy to our home account'><![CDATA[
<copy xmlns='http://jabber.org/protocol/filter/basic'>me@home.com</copy>
]]></example>

</section1>

<section1 topic='Security Considerations'>
  <p>There are no security features or concerns related to this proposal.</p>
</section1>

<section1 topic='IANA Considerations'>
  <p>This document requires no interaction with the IANA.</p>
</section1>

<section1 topic='JANA Considerations'>
  <p>No namespaces or parameters need to be registered with JANA as a result of this document.</p>
</section1>

</xep>
