=== xsf/xeps/inbox/xep.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--

Copyright (c) 1999 - 2010 XMPP Standards Foundation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

-->

<!ELEMENT xep ( header, section1* ) >
<!ATTLIST xep
          xmlns CDATA '' >
<!ELEMENT header ( title, abstract, legal, number, status, lastcall*, interim*, type, sig, approver*, dependencies, supersedes, supersededby, shortname, schemaloc*, registry?, discuss?, expires?, author+, revision+, councilnote? ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT abstract (#PCDATA)* >
<!ELEMENT legal ( copyright, permissions, warranty, liability, conformance ) >
<!ELEMENT copyright (#PCDATA | link)* >
<!ELEMENT permissions (#PCDATA | link)* >
<!ELEMENT warranty (#PCDATA | link)* >
<!ELEMENT liability (#PCDATA | link)* >
<!ELEMENT conformance (#PCDATA | link)* >
<!ELEMENT number (#PCDATA)* >
<!ELEMENT status (#PCDATA)* >
<!ELEMENT lastcall (#PCDATA)* >
<!ELEMENT interim EMPTY>
<!ELEMENT type (#PCDATA)* >
<!ELEMENT sig (#PCDATA)* >
<!ELEMENT approver (#PCDATA)* >
<!ELEMENT dependencies ( spec* ) >
<!ELEMENT supersedes ( spec? ) >
<!ELEMENT supersededby ( spec? ) >
<!ELEMENT spec (#PCDATA)* >
<!ELEMENT shortname (#PCDATA)* >
<!ELEMENT schemaloc ( ns?, url ) >
<!ELEMENT ns (#PCDATA)* >
<!ELEMENT url (#PCDATA)* >
<!ELEMENT registry EMPTY>
<!ELEMENT discuss (#PCDATA)* >
<!ELEMENT expires (#PCDATA)* >
<!ELEMENT author ( firstname, surname, authornote?, org?, email?, jid?, uri? ) >
<!ELEMENT firstname (#PCDATA)* >
<!ELEMENT surname (#PCDATA)* >
<!ELEMENT authornote EMPTY>
<!ELEMENT org (#PCDATA)* >
<!ELEMENT email (#PCDATA)* >
<!ELEMENT jid (#PCDATA)* >
<!ELEMENT uri (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark ( p | ul )* >
<!ELEMENT councilnote (#PCDATA)* >
<!ELEMENT section1 ( div | p | section2 | example | code | ul | ol | dl | table )* >
<!ATTLIST section1
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section2 ( div | p | section3 | example | code | ul | ol | dl | table )* >
<!ATTLIST section2
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section3 ( div | p | section4 | example | code | ul | ol | dl | table )* >
<!ATTLIST section3
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section4 ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST section4
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT div ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST div 
          class CDATA ''
          style CDATA '' >
<!ELEMENT p (#PCDATA | br | img | link | note | tt | dfn | em | strong | cite | span)* >
<!ATTLIST p 
          class CDATA ''
          style CDATA '' >
<!ELEMENT br EMPTY >
<!ELEMENT ul (li+) >
<!ATTLIST ul 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT ol (li+) >
<!ATTLIST ol 
          class CDATA '' 
          start CDATA '' 
          style CDATA '' >
<!ELEMENT li (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ATTLIST li 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT dl (di+) >
<!ELEMENT di ( dt, dd ) >
<!ELEMENT dt (#PCDATA)* >
<!ELEMENT dd (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA '' >
<!ELEMENT link (#PCDATA)* >
<!ATTLIST link url CDATA '' >
<!ELEMENT note (#PCDATA | link | tt | dfn | em | strong | cite | span)* >
<!ELEMENT example (#PCDATA)* >
<!ATTLIST example caption CDATA '' >
<!ELEMENT code (#PCDATA)* >
<!ATTLIST code caption CDATA '' >
<!ELEMENT table (tr)* >
<!ATTLIST table caption CDATA '' >
<!ELEMENT tr ( th | td )* >
<!ELEMENT th (#PCDATA)* >
<!ATTLIST th 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT td (#PCDATA)* >
<!ATTLIST td 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT tt (#PCDATA)* >
<!ELEMENT dfn (#PCDATA)* >
<!ELEMENT em (#PCDATA)* >
<!ELEMENT strong (#PCDATA)* >
<!ELEMENT cite (#PCDATA)* >
<!ELEMENT span (#PCDATA | link | tt | dfn | em | strong )* >
<!ATTLIST span 
          class CDATA ''
          style CDATA '' >

=== xsf/xeps/inbox/baseline-security.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
        <!ENTITY % ents SYSTEM 'xep.ent'>
        %ents;
        ]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
    <header>
        <title>Improving Baseline Security in XMPP</title>
        <abstract>This document describes a number of concrete and effective mechanisms for offering significant security enhancements to XMPP, with broad applicability.</abstract>
        &LEGALNOTICE;
        <number>XXXX</number>
        <status>ProtoXEP</status>
        <type>Humorous</type>
        <sig>Standards</sig>
        <dependencies>
            <spec>XMPP Core</spec>
        </dependencies>
        <supersedes/>
        <supersededby/>
        <shortname>security-theatre</shortname>
        <author>
            <firstname>Chris</firstname>
            <surname>Davidland</surname>
            <email>chris.davidland@crap-security.example</email>
            <jid>chris.davidland@crap-security.example</jid>
        </author>
        <author>
            <firstname>Lucas</firstname>
            <surname>George</surname>
            <email>lucas.george@shiteam.example</email>
            <jid>lucas.george@shiteam.example</jid>
        </author>
        <revision>
            <version>0.0.1</version>
            <date>2019-04-01</date>
            <initials>cd/lg</initials>
            <remark>
                <ul>
                    <li>Initial Revision</li>
                </ul>
            </remark>
        </revision>
    </header>

    <section1 topic='Introduction' anchor='intro'>
        <p>During the early part of 2019, the Security High Intelligence Team at the Centre for Research and Promotion of Security conducted a detailed survey of existing security practises within XMPP deployments, and observed a number of areas where improvements could be made.</p>
        <p>After a period of intensive development, we present our findings, along with concrete, proven mechanisms for dramatically uplifting security within XMPP software and deployments, to the community.</p>
    </section1>

    <section1 topic="Requirements" anchor="reqs">
        <p>As general aims, we wish to ensure:</p>
        <ul>
            <li>All communication should occur over properly encrypted links.</li>
            <li>Data should be encrypted using industry-standard ciphers across both links and end-to-end.</li>
        </ul>
    </section1>

    <section1 topic='Particulars'>
        <section2 topic="Legacy Namespaces">
            <p>XMPP has a great many XML namespaces (See &w3xmlnamespaces;) which are used as the mechanism by which the core protocol has been extended. Many of the older namespaces are, however, denoted by URIs with an "http" scheme (See &rfc2616; et passim). Clearly these are insecure, as the namespace would be served in the clear, and could easily be subverted by a malicious third party. Therefore, we propose that these XML namespaces are replaced with upgraded ones running over TLS, by using the "https" scheme (See &rfc2818;).</p>
            <p>While somewhat disruptive to existing deployments, the clear security benefits outweigh any such concerns.</p>
        </section2>
        <section2 topic="New-style Namespaces">
            <p>Newer extensions have used URNs within the "urn:xmpp" namespace. Pursuant to &xep0368;, the previously legacy "xmpps" would offer immediate security benefits to such namespaces. Traditional "urn:xmpp" namespaces, while often capable of TLS transports, can only offer such security in a feature advertisement, and as such a naive namespace client can be the target of a downgrade attack.</p>
            <p>There is a clear temptation to suggest we should concentrate on ensuring namespace clients are simply more security aware, but reviving XMPPS, just as &xep0368; has done, offers a straightforward mechanism for promoting a step increase in security.</p>
        </section2>
        <section2 topic="Stanza Encryption">
            <p>A pressing limitation of existing deployed end-to-end encryption techniques is a lack of full stanza encryption. While &xep0374; does encrypt much of the stanza, although not all, &xep0384; encrypts only the &lt;body/> element's contents.</p>
            <p>Clearly neither is sufficient for high security applications, and therefore we propose encrypting the stanza heavily. A detailed survey of supported encryption algorithms suggests that Double ROT-13 is widely supported and available on all platforms. This cipher has the signficant benefit that encryption is entirely transparent, providing excellent interoperability benefits with older implementations that may not have been upgraded.</p>
            <p>We therefore recommend that all stanzas on the wire are fully encrypted with Double ROT-13. Given the following stanza:</p>
            <example caption="Original unencrypted stanza"><![CDATA[
  <message from='chris.davidland@crap-security.example' to='lucas.george@shiteam.example' type='chat' id='12345'>
    <some-metadata xmlns='urn:xmpps:example:metadata'/>
    <body>Hey, Lucas!</body>
  </message>
]]>
            </example>
            <p>The following shows a correctly encrypted stanza:</p>
            <example caption="Stanza with encrypted meta-data and payload"><![CDATA[
  <message from='chris.davidland@crap-security.example' to='lucas.george@shiteam.example' type='chat' id='12345'>
    <some-metadata xmlns='urn:xmpps:example:metadata'/>
    <body>Hey, Lucas!</body>
  </message>
]]>
            </example>
            <p>The following, however, has only encrypted the body text - this is NOT valid encryption, and an attacker can easily read the remaining metadata!</p>
            <example caption="Stanza with encrypted body payload"><![CDATA[
  <message from='chris.davidland@crap-security.example' to='lucas.george@shiteam.example' type='chat' id='12345'>
    <some-metadata xmlns='urn:xmpps:example:metadata'/>
    <body>Hey, Lucas!</body>
  </message>
]]>
            </example>
            <p>In the following example, while the entire contents of the stanza have been correctly encrypted, the outer stanza tag itself remains in the clear. An attacker could, therefore, trivially discover key metadata such as the sender, type, and id of the message.</p>
            <example caption="Stanza with encrypted elements"><![CDATA[
  <message from='chris.davidland@crap-security.example' to='lucas.george@shiteam.example' type='chat' id='12345'>
    <some-metadata xmlns='urn:xmpps:example:metadata'/>
    <body>Hey, Lucas!</body>
  </message>
]]>
            </example>
        </section2>
    </section1>
    <section1 topic='Security Considerations' anchor='security'>
        <p>The entirely of this document is concerned with security.</p>
    </section1>

    <section1 topic='IANA Considerations' anchor='iana'>
        <p>If adopted into the Standards Track, the URN "urn:xmpps" is required to be registered with &IANA;. </p>
    </section1>

    <section1 topic='XMPP Registrar Considerations' anchor='registrar'>
        <p>If adopted into the Standards Track, every protocol's namespace is required to be changed, and this should be reflected in the registry.</p>
    </section1>

    <section1 topic='Acknowledgements' anchor='ack'>
        <p>The authors wish to acknowledge the great efforts being made elsewhere to improve the security of XMPP, and hope this specification complements their efforts suitably.</p>
    </section1>

</xep>

=== xsf/xeps/xep-0430.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
        <!ENTITY ns "urn:xmpp:inbox:1">
        <!ENTITY nsx "urn:example:">
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Inbox</title>
  <abstract>This specification proposes a mechanism by which clients can find a list of ongoing conversations and their state.</abstract>
  &LEGALNOTICE;
  <number>0430</number>
  <status>Deferred</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XEP-0313</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>inbox</shortname>
  &dcridland;
  <revision>
    <version>0.2.0</version>
    <date>2020-02-03</date>
    <initials>dwd</initials>
    <remark>Updates from the Summit 24 discussion:
      <ul>
        <li>Remove Marked</li>
        <li>Metadata in sibling</li>
        <li>Ensure the last "mam id" is present in metadata, and describe how that can be used.</li>
        <li>Add options to control unread-only and elide messages.</li>
      </ul>
    </remark>
  </revision>
  <revision>
    <version>0.1.0</version>
    <date>2020-01-29</date>
    <initials>XEP Editor (jsc)</initials>
    <remark>Accepted by vote of Council on 2020-01-22.</remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2019-12-30</date>
    <initials>dwd</initials>
    <remark>
      <ul>
        <li>Initial Revision</li>
      </ul>
    </remark>
  </revision>
</header>

<section1 topic='Introduction' anchor='intro'>
  <p>When initially run, a messaging client typically shows some list of contacts and chatrooms, and whether any new
    messages are present in each.</p>
  <p>The current mechanism for achieving this UX involves a complete synchronization of the server-side archive, and is both
    time-consuming and bandwidth-intensive. This specification proposes a solution to directly obtain such data from
    the server.</p>
  <p>Moreover, the information gathered by the server to support this can be used in support of mobile push notifications.</p>
  <section2 topic="Terminology">
    <p>Nomenclature used for instant messages versus ancillary messages will need to be adjusted to make it consistent
      with &xep0422; et al.</p>
  </section2>
</section1>

<section1 topic='Overview' anchor="overview">
  <section2 topic="Discovering Support" anchor="feature">
    <p>Support for this protocol is advertised by the Service Discovery protocol defined in &xep0030; using a feature
      of <tt>&ns;</tt>.</p>
  </section2>
  <section2 topic="The Inbox">
    <p>The Inbox consists semantically of a list of conversations in order of last activity. Each conversation is
      identified by a jid - for group chats this would be the chatroom, and for individual contacts this would be their
      bare jid.</p>
    <p>Each Inbox entry includes a count of messages considered new, the last MAM stanza-id relating to this conversation,
      and the last MAM result for this conversation, as defined by &xep0313;. In addition, a client-controlled boolean
      marker can be used to indicate a manual "set unread" state.</p>
    <p>Finding more messages from this conversation can be achieved via a MAM query using <tt>with</tt> to specify the
      conversation required.</p>
  </section2>
</section1>

  <section1 topic="Protocol Elements">
    <section2 topic="Querying">
      <p>An &IQ; of type "get" is used, containing a single element <tt>&lt;inbox/></tt>, containing an optional RSM
        filter as specified by &xep0059;. This will typically be sent only to the user's own bare jid. If a client
        requests the inbox without RSM, the server MAY limit the number of conversations arbitrarily by either time or number. This element has a number of attributes:</p>
      <ul>
        <li><tt>unread-only</tt> - Defaults to false. If true, the server will list only conversations with at least one unread message.</li>
        <li><tt>messages</tt> - Defaults to true. If true, the server includes the last message; if false, this is elided.</li>
      </ul>
      <p>The server
        responds with a sequence of &MESSAGE; stanzas, each containing an <tt>&lt;entry/></tt> element qualified by the
        <tt>&ns;</tt> namespace with a number of attributes:</p>
      <ul>
        <li><tt>jid</tt> - contains the Jid of the conversation for this entry.</li>
        <li><tt>unread</tt> - contains a count of messages which are deemed to be unread by the server. Clients may use this to indicate unread messages to the user.</li>
        <li><tt>id</tt> - contains the last id in the MAM archive for this conversation. Clients may use this as a marker to fetch additional messages (or collated fastenings, see &xep0427;) about the conversation via MAM.</li>
      </ul>
      <p>If the <tt>messages</tt> attribute is missing or set to <tt>true</tt>, the <tt>&lt;entry/></tt> element is followed by the latest instant message, if any, which is encapsulated as a
        <tt>&lt;result/></tt> element as defined by &xep0313;. This contains collated fastenings if supported by the
        server.</p>
      <p>After all entries required have been returned, the server then responds with an &IQ; result containing a
        <tt>&lt;fin/></tt> element qualified by <tt>&ns;</tt>. This contains the RSM data, a total count of conversation
        entries within the inbox, a count of conversations with unread messages, and a total count of unread messages.</p>
    </section2>
  </section1>

  <section1 topic="Unread Messages">
    <p>Servers MUST track which instant messages sent to clients remain unread.</p>
    <ul>
      <li>An instant message is always read if it is followed by an instant message which is read.</li>
      <li>An instant message always starts unread.</li>
      <li>A Chat Marker (see &xep0333;) of "displayed" or "acknowledged" causes the message to be read (and also causes
      all prior messages to be read by implication).</li>
      <li>A Message Receipt (see &xep0184;) does not cause messages to be considered unread.</li>
      <li>Unmarking a conversation always sets the unread counter to zero, and by implication sets all messages to be
        read.</li>
    </ul>
  </section1>

  <section1 topic="Examples">
    <p>Let us assume a user has only three jids they have exchanged messages with. Asking for their inbox is simple:</p>
    <example><![CDATA[
    <iq type='get' id='iq_stanza_id'>
      <inbox xmlns=']]>&ns;<![CDATA['/>
    </iq>
    ]]></example>
    <p>The server responds with a list of conversations:</p>
    <example><![CDATA[
    <message>
      <entry xmlns=']]>&ns;<![CDATA[' unread='5' jid='first_contact@example.net' id='uuid-1'/>
      <result xmlns='urn:xmpp:mam:2' queryid='iq_stanza_id' id='uuid-1'>
        <forwarded xmlns='urn:xmpp:forward:0'>
          <message xmlns='jabber:client' from='first_contact@example.net' to='user@example.org' type='chat'>
            <body>Greetings from Alpha Centauri!</body>
          </message>
        </forwarded>
      </result>
    </message>

    <message>
      <entry xmlns=']]>&ns;<![CDATA[' unread='0' jid='second_contact@example.net' id='uuid-5'/>
      <result xmlns='urn:xmpp:mam:2' queryid='iq_stanza_id' id='uuid-5'>
        <forwarded xmlns='urn:xmpp:forward:0'>
          <message xmlns='jabber:client' from='second_contact@example.net' to='user@example.org' type='chat'>
            <body>Greetings from Mars!</body>
          </message>
        </forwarded>
      </result>
    </message>

    <message>
      <entry xmlns=']]>&ns;<![CDATA[' unread='1' jid='third_contact@example.net' id='uuid-8'/>
      <result xmlns='urn:xmpp:mam:2' queryid='iq_stanza_id' id='uuid-8'>
        <forwarded xmlns='urn:xmpp:forward:0'>
          <message xmlns='jabber:client' from='third_contact@example.net' to='user@example.org' type='chat'>
            <body>Greetings from Somewhere Else!</body>
          </message>
        </forwarded>
      </result>
    </message>
    ]]></example>
    <p>If the <tt>id</tt> of a conversation has changed, a client might fetch the missing messages and metadata by requesting the MAM archive <tt>with</tt> the <tt>jid</tt> of the entry, and <tt>after</tt> the previous known <tt>id</tt> for the conversation.</p>
    <p>After the list of conversations, the server completes its response with a the reply to the original IQ.</p>
    <example><![CDATA[
      <iq type='result' id='iq_stanza_id'>
        <fin xmlns=']]>&ns;<![CDATA[' total='3' unread='2' all-unread='6'>
          <!-- RSM -->
        </fin>
    ]]></example>
  </section1>

  <section1 topic="Schema">
    <p>TODO - Hopefully roughly given by the examples.</p>
  </section1>

<section1 topic='Security Considerations' anchor='security'>
  <p>TODO</p>
</section1>

<section1 topic='IANA Considerations' anchor='iana'>
  <p>This XEP requires no interaction with &IANA;. </p>
</section1>

<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>None.</p>
</section1>

<section1 topic='Acknowledgements' anchor='ack'>
  <p>The author notes that this protocol is heavily based on the <tt>mod_inbox</tt> system of MongooseIM. In addition, Kevin Smith and several others at the XMPP Summit 24 provided useful feedback which has shaped this specification.</p>
</section1>

</xep>

=== xsf/xeps/xep-0007.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM "xep.ent">
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Conferencing SIG</title>
  <abstract>A proposal for a Jabber Interest Group that will discuss the protocol for implementing many-to-many communications.</abstract>
  &LEGALNOTICE;
  <number>0007</number>
  <status>Obsolete</status>
  <type>SIG Proposal</type>
  <sig>Conferencing</sig>
  <approver>Board</approver>
  <dependencies/>
  <supersedes/>
  <supersededby/>
  <shortname>N/A</shortname>
  <author>
    <firstname>David</firstname>
    <surname>Waite</surname>
    <email>akuma@jabber.org</email>
    <jid>akuma@jabber.org</jid>
  </author>
  <revision>
    <version>1.1</version>
    <date>2002-05-08</date>
    <initials>psa</initials>
    <remark>Changed Status to Obsolete per approval of XEP-0019.</remark>
  </revision>
  <revision>
    <version>1.0</version>
    <date>2001-08-03</date>
    <initials>akuma</initials>
    <remark>Initial version</remark>
  </revision>
</header>
<section1 topic='Introduction'>
  <p>The following proposal is for the formation of a Jabber Interest Group that will create a new conferencing protocol, as well as create additional functionality and standardize communications on top of said conferencing protocol.</p>
</section1>
<section1 topic='Base conferencing protocol'>
  <p>The initial task of the Conferencing SIG will be to propose a Jabber Conferencing specification that will solve various problems which exist in the current "groupchat" specification. This specification is meant to be a foundation for additional functionality; it defines the framework needed to provide additional features, without requiring changes to the framework specification itself. There is also to be a certain amount of feature-negotiation included; the conferencing service can define what features can be declared for a room, both as optional and required client features for room participation.</p>
  <p>The framework's scope consists of the following minimum functionality:</p>
  <ul>
    <li>Browsing a list of public rooms</li>
    <li>Finding a public room based on search parameters</li>
    <li>Creating new rooms</li>
    <li>Destroying rooms</li>
    <li>Entering existing rooms</li>
    <li>Altering functionality of a room</li>
    <li>Querying a room for public information</li>
    <li>Sending and accepting invitations to a room</li>
    <li>Changing a participant's nickname within a room</li>
    <li>Discovering and changing features on a running room</li>
    <li>Changing a participant's status within a room</li>
    <li>Sending a message to a room or a specific participant within a room</li>
  </ul>
  <p>In addition to these basic functions, we can imagine numerous different types of conferencing features; for example, hidden rooms created on the fly for discussions between a Jabber user and their friends or co-workers, transports providing access to similar foreign systems such as IRC, additional client functionality such as shared-location (URL/Co-browsing) and whiteboarding, and so on. There might also be requirements for security levels (for instance, normal participant, moderator, and room admin).  Additional information may also be conveyed to users about one another, such as a user's real Jabber ID. Room entry or participation within a discussion might also have restrictions on some systems.</p>
  <p>The framework protocol is meant to provide a basis for designing these additional features. Some features, such as co-browsing, could be implemented entirely client-side; others may require significant logic within the conferencing implementation. In addition, some features may be optional for participation within a room, while other features could be required in order for a client to participate within a room.</p>
</section1>
<section1 topic='Justification for new Conferencing protocol'>
  <p>While the current "groupchat" specification is rather simple to implement, it is rather inflexible and cannot easily be extended; specifically, it has the following disadvantages:</p>
  <ul>
    <li>There is no control over how you enter a room - for instance, you can not specify a password for entering a password-protected room.</li>
    <li>There is no way to create a room without entering it, and no way to tell the state of the room without being a participant within it. This means among other things that a client can not transparently use groupchat for starting multi-user chats.</li>
    <li>Changes in room state are often conveyed via text messages rather than XML.  Among other things, this limits the display of messages to the English language and limits a client author's freedom in displaying this information.</li>
    <li>A Participant's entry into a room is abstracted from their real Jabber account in both the old and new protocols; however, "groupchat" provides no way of tracking users across nickname changes or across sessions within a conference room.</li>
    <li>The "groupchat" protocol has no way of performing feature negotiation (e.g., specifying the additional protocol elements needed to participate in a room, or optionally allowed from participants within a room). If there were participants with clients sending custom data through the room (such as XHTML or whiteboarding), you would receive that information even without your client being able to support it, and have no way of distinguishing altered behavior due to additional features of a "groupchat" implementation.</li>
  </ul>
  <p>This new conferencing protocol will be designed to solve these problems.</p>
  <p>Because of the prevalence of the existing "groupchat" specification for multi-user chats, a long conversion process is anticipated.  A server implementation which supports both protocols will simply not allow "groupchat"-only clients to participate in rooms with required features.</p>
</section1>
<section1 topic='Continuing Development'>
  <p>As listed above, there is a fairly large number of features that could be developed on top of a well-designed framework. The Conferencing SIG will first be established to develop a framework, with features mainly being compared against the framework for feasibility of implementation. After a proposal has been formalized as a specification, the SIG will become a group for discussing and proposing new features, and for formally specifying those features.</p>
</section1>
</xep>
