=== xsf/xeps/inbox/xep.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--

Copyright (c) 1999 - 2010 XMPP Standards Foundation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

-->

<!ELEMENT xep ( header, section1* ) >
<!ATTLIST xep
          xmlns CDATA '' >
<!ELEMENT header ( title, abstract, legal, number, status, lastcall*, interim*, type, sig, approver*, dependencies, supersedes, supersededby, shortname, schemaloc*, registry?, discuss?, expires?, author+, revision+, councilnote? ) >
<!ELEMENT title (#PCDATA)* >
<!ELEMENT abstract (#PCDATA)* >
<!ELEMENT legal ( copyright, permissions, warranty, liability, conformance ) >
<!ELEMENT copyright (#PCDATA | link)* >
<!ELEMENT permissions (#PCDATA | link)* >
<!ELEMENT warranty (#PCDATA | link)* >
<!ELEMENT liability (#PCDATA | link)* >
<!ELEMENT conformance (#PCDATA | link)* >
<!ELEMENT number (#PCDATA)* >
<!ELEMENT status (#PCDATA)* >
<!ELEMENT lastcall (#PCDATA)* >
<!ELEMENT interim EMPTY>
<!ELEMENT type (#PCDATA)* >
<!ELEMENT sig (#PCDATA)* >
<!ELEMENT approver (#PCDATA)* >
<!ELEMENT dependencies ( spec* ) >
<!ELEMENT supersedes ( spec? ) >
<!ELEMENT supersededby ( spec? ) >
<!ELEMENT spec (#PCDATA)* >
<!ELEMENT shortname (#PCDATA)* >
<!ELEMENT schemaloc ( ns?, url ) >
<!ELEMENT ns (#PCDATA)* >
<!ELEMENT url (#PCDATA)* >
<!ELEMENT registry EMPTY>
<!ELEMENT discuss (#PCDATA)* >
<!ELEMENT expires (#PCDATA)* >
<!ELEMENT author ( firstname, surname, authornote?, org?, email?, jid?, uri? ) >
<!ELEMENT firstname (#PCDATA)* >
<!ELEMENT surname (#PCDATA)* >
<!ELEMENT authornote EMPTY>
<!ELEMENT org (#PCDATA)* >
<!ELEMENT email (#PCDATA)* >
<!ELEMENT jid (#PCDATA)* >
<!ELEMENT uri (#PCDATA)* >
<!ELEMENT revision ( version, date, initials, remark ) >
<!ELEMENT version (#PCDATA)* >
<!ELEMENT date (#PCDATA)* >
<!ELEMENT initials (#PCDATA)* >
<!ELEMENT remark ( p | ul )* >
<!ELEMENT councilnote (#PCDATA)* >
<!ELEMENT section1 ( div | p | section2 | example | code | ul | ol | dl | table )* >
<!ATTLIST section1
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section2 ( div | p | section3 | example | code | ul | ol | dl | table )* >
<!ATTLIST section2
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section3 ( div | p | section4 | example | code | ul | ol | dl | table )* >
<!ATTLIST section3
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT section4 ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST section4
          topic CDATA '' 
          anchor CDATA '' >
<!ELEMENT div ( div | p | example | code | ul | ol | dl | table )* >
<!ATTLIST div 
          class CDATA ''
          style CDATA '' >
<!ELEMENT p (#PCDATA | br | img | link | note | tt | dfn | em | strong | cite | span)* >
<!ATTLIST p 
          class CDATA ''
          style CDATA '' >
<!ELEMENT br EMPTY >
<!ELEMENT ul (li+) >
<!ATTLIST ul 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT ol (li+) >
<!ATTLIST ol 
          class CDATA '' 
          start CDATA '' 
          style CDATA '' >
<!ELEMENT li (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ATTLIST li 
          class CDATA '' 
          style CDATA '' >
<!ELEMENT dl (di+) >
<!ELEMENT di ( dt, dd ) >
<!ELEMENT dt (#PCDATA)* >
<!ELEMENT dd (#PCDATA | p | link | note | tt | em | strong | span)* >
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA '' >
<!ELEMENT link (#PCDATA)* >
<!ATTLIST link url CDATA '' >
<!ELEMENT note (#PCDATA | link | tt | dfn | em | strong | cite | span)* >
<!ELEMENT example (#PCDATA)* >
<!ATTLIST example caption CDATA '' >
<!ELEMENT code (#PCDATA)* >
<!ATTLIST code caption CDATA '' >
<!ELEMENT table (tr)* >
<!ATTLIST table caption CDATA '' >
<!ELEMENT tr ( th | td )* >
<!ELEMENT th (#PCDATA)* >
<!ATTLIST th 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT td (#PCDATA)* >
<!ATTLIST td 
          colspan CDATA ''
          rowspan CDATA '' >
<!ELEMENT tt (#PCDATA)* >
<!ELEMENT dfn (#PCDATA)* >
<!ELEMENT em (#PCDATA)* >
<!ELEMENT strong (#PCDATA)* >
<!ELEMENT cite (#PCDATA)* >
<!ELEMENT span (#PCDATA | link | tt | dfn | em | strong )* >
<!ATTLIST span 
          class CDATA ''
          style CDATA '' >

=== xsf/xeps/xep-0352.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Client State Indication</title>
  <abstract>This document defines a way for the client to indicate its active/inactive state.</abstract>
  &LEGALNOTICE;
  <number>0352</number>
  <status>Experimental</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <approver>Council</approver>
  <dependencies>
    <spec>XMPP Core</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>NOT_YET_ASSIGNED</shortname>
  &mwild;
  <revision>
    <version>next</version>
    <date>2015-XX-XX</date>
    <initials>fs</initials>
    <remark><p>Add message notification send by server to client about CSI state.</p></remark>
  <revision>
    <version>0.1</version>
    <date>2014-08-28</date>
    <initials>XEP Editor (asw)</initials>
    <remark><p>Initial published version approved by the XMPP Council.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2014-08-14</date>
    <initials>mw</initials>
    <remark><p>First draft.</p></remark>
  </revision>
</header>

<section1 topic='Introduction' anchor='intro'>
  <p>It is common for IM clients to be logged in and 'online' even while the user is not interacting with the application. This
  protocol allows the client to indicate to the server when the user is not actively using the client, allowing the server to
  optimise traffic to the client accordingly. This can save bandwidth and resources on both the client and server.</p>
</section1>

<section1 topic='Requirements' anchor='reqs'>
  <p>The aim of this specification is to provide a simple and efficient protocol for the client to report its
  state to the server. Exactly how the server uses this information is beyond the scope of this document, although
  some examples are given.</p>
  <p>Other extensions exist, such as &xep0273;, which also aim to optimise the traffic between the client and server.
  A notable difference is that instead of being client-controlled, CSI shifts the responsibility to the server, and
  aims to just provide the server with enough information to implement various optimisations itself.</p>
</section1>

<section1 topic='Use Cases' anchor='usecases'>
  <section2 topic='User and client behaviour' anchor='behaviour-user'>
    <p>Juliet has an XMPP client on her phone, which is available to receive messages. However most of the time
    Juliet has her phone screen turned off and is not interested in the status of her contacts unless they are
    communicating with her.</p>
  
    <p>Juliet's client informs the server when Juliet is not interacting with it. The server uses this information to
    suppress or reduce stanzas that are unimportant, such as status updates.</p>
  
    <p>When Juliet returns to her IM client, the client again informs the server, this time to report that it is active
    again. The server then disables its traffic optimisations and restores the stream to its normal state.</p>
  </section2>
  <section2 topic="Server behaviour">
    <p>When the server knows that the user is not engaging with their client many optimisations become possible. For
    example a server could:</p>
    <ul>
    <li>Suppress presence updates until the client becomes active again. On becoming active, push the latest
    presence from each contact.</li>
    <li>Discard messages containing only &xep0085; payloads.</li>
    <li>Defer or discard unimportant PEP notifications, possibly unsubscribe from certain PEP nodes
    until the client becomes active again.</li>
    </ul>

    <p>This list is for example only, a server is not required to implement all or any of these, nor is it prevented
    from implementing other behaviour not listed here. Regardless of what optimisations a server implements, it SHOULD
    provide a way for administrators to configure them, and MAY provide such configuration to users also (e.g., through an
    ad-hoc command).</p>
  </section2>
</section1>
<section1 topic="Protocol" anchor="protocol">
  <section2 topic="Discovering support" anchor="discovery">
    <p>If the server supports CSI, it advertises it in the stream features after the client has authenticated:</p>
    <example caption='Server indicates support for CSI'><![CDATA[
<stream:features>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>
  <csi xmlns='urn:xmpp:csi:0'/>
</stream:features>]]></example>
  </section2>

  <section2 topic="Indicating state to the server" anchor="indication">
    <p>A stream always begins in 'active' state. If a client wishes to inform the server that it has become inactive,
    it sends an &lt;inactive/&gt; element in the 'urn:xmpp:csi:0' namespace:</p>
    <example caption='Client indicates it is inactive'><![CDATA[
<inactive xmlns='urn:xmpp:csi:0'/>]]></example>
    
    <p>As might be anticipated, when the client is active again it sends an &lt;active/&gt; element:</p>
    <example caption='Client indicates it is active'><![CDATA[
<active xmlns='urn:xmpp:csi:0'/>]]></example>
  </section2>

  <section2 topic="Server state notification to the client" anchor="server-notification">
    <p>The server MUST signal the completion of the client state transition by sending a message indicating that the CSI state changed to the full JID which requested the change, once he performed all actions necessary to change the state. The message must contain a &lt;notification/&gt; element qualified by the 'urn:xmpp:csi:1' namespace, containing either an &lt;active/&gt; or &lt;inactive/&gt; child element. The receiving client MUST NOT make any assumption about the message type of the message containing the &lt;notification/&gt; element. The 'from' attribute of the message MUST be empty.</p>
	<example caption='Server notifies the client about a completed change of the CSI state'><![CDATA[
<message to='client@examle.org/resource'>
  <notification xmlns='urn:xmpp:csi:1'>
    <active/>
  </notification>
</message>]]></example>
	<p>CSI enabled Servers MUST send an &lt;active/&gt; CSI notification after stream resumption (&xep0198;), in order to override possible pending inactive notifications in the stream's queue. Therefore CSI notification receiving entites MUST be prepared to receive CSI notifications at any time, e.g. even if no CSI state change was previously requested.</p>
  </section2>
</section1>
<section1 topic='Business Rules' anchor='rules'>
  <p>As this protocol is for indication only, clients MUST NOT make assumptions about how the server
  will use the active/inactive state information.</p>
  
  <p>The server MUST assume all clients to be in the 'active' state until the client indicates otherwise. Also the
  CSI active/inactive state is unrelated to the user's presence, the server MUST treat the two independently.</p>
  
  <p>This protocol is intended primarily for clients with human interaction. Due to the open-ended nature of
  the possible optimisations implemented by the server, it may not be suitable for non-IM purposes where the
  fully standard behaviour of XMPP is required.</p>

  <p>The CSI state MUST NOT be keept when a stream is resumed by means of <cite>Stream Management (XEP-0198) ยง 5. Resumption</cite>;. If a stream is resumed by a client, it is always in 'active' state.</p>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>To protect the privacy of users, servers MUST NOT reveal the clients active/inactive state to other
  entities on the network.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>This document requires no interaction with &REGISTRAR;.</p>
</section1>
<section1 topic='XML Schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='urn:xmpp:csi:0'
    xmlns='urn:xmpp:csi:0'
    elementFormDefault='qualified'>

  <xs:element name='csi' type='empty'/>
  <xs:element name='active' type='empty'/>
  <xs:element name='inactive' type='empty'/>

  <xs:simpleType name='empty'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value=''/>
    </xs:restriction>
  </xs:simpleType>

  <!-- TODO add schema for message stanza 'csi' extension element -->
</xs:schema>
    ]]></code>
</section1>
</xep>

=== xsf/xeps/xep-0213.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>XMPP Intermediate IM Client 2008</title>
  <abstract>This document defines the XMPP Intermediate IM Client 2008 compliance level.</abstract>
  &LEGALNOTICE;
  <number>0213</number>
  <status>Obsolete</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XEP-0211</spec>
    <spec>XEP-0016</spec>
    <spec>XEP-0045</spec>
    <spec>XEP-0054</spec>
    <spec>XEP-0085</spec>
    <spec>XEP-0155</spec>
  </dependencies>
  <supersedes/>
  <supersededby>
    <spec>XEP-0242</spec>
  </supersededby>
  <shortname>N/A</shortname>
  &stpeter;
  <revision>
    <version>1.0</version>
    <date>2007-07-11</date>
    <initials>psa</initials>
    <remark><p>Per a vote of the XMPP Council, advanced to Draft.</p></remark>
  </revision>
  <revision>
    <version>0.5</version>
    <date>2007-07-11</date>
    <initials>psa</initials>
    <remark><p>Added XEP-0155 as recommended.</p></remark>
  </revision>
  <revision>
    <version>0.4</version>
    <date>2007-06-11</date>
    <initials>psa</initials>
    <remark><p>Added implementation notes.</p></remark>
  </revision>
  <revision>
    <version>0.3</version>
    <date>2007-05-30</date>
    <initials>psa</initials>
    <remark><p>Per list discussion, removed XHTML-IM.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2007-05-11</date>
    <initials>psa</initials>
    <remark><p>Per list discussion, modified MUC support, added privacy lists, and added vCard support.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2007-04-20</date>
    <initials>psa</initials>
    <remark><p>Initial published version.</p></remark>
  </revision>
  <revision>
    <version>0.0.1</version>
    <date>2007-03-30</date>
    <initials>psa</initials>
    <remark>First draft, split from XEP-0117.</remark>
  </revision>
</header>
<section1 topic='Introduction' anchor='intro'>
  <p>The &XSF; defines protocol suites for the purpose of compliance testing and software certification. This document specifies the XMPP Intermediate IM Client 2008 certification level.</p>
</section1>
<section1 topic='Definition' anchor='def'>
  <p>The XMPP Intermediate IM Client 2008 certification level is defined as follows:</p>
  <table caption='Required and Recommended Specifications'>
    <tr>
      <th>Specification</th>
      <th>Requirement Level</th>
    </tr>
    <tr>
      <td>&xep0211;</td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td><strong>&xep0016;</strong></td>
      <td>RECOMMENDED</td>
    </tr>
    <tr>
      <td>&xep0045;, Entity Use Cases and Occupant Use Cases</td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td>&xep0054;</td>
      <td>RECOMMENDED</td>
    </tr>
    <tr>
      <td>&xep0085;</td>
      <td>REQUIRED</td>
    </tr>
    <tr>
      <td>&xep0155;</td>
      <td>RECOMMENDED</td>
    </tr>
  </table>
</section1>
<section1 topic='Implementation Notes' anchor='impl'>
  <p>Some of the protocol specifications referenced herein have their own dependencies; developers must refer to the relevant specifications for further information.</p>
</section1>
<section1 topic='Security Considerations' anchor='security'>
  <p>This document introduces no additional security considerations above and beyond those defined in the documents on which it depends.</p>
</section1>
<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>
<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <p>This document requires no interaction with the &REGISTRAR;.</p>
</section1>
</xep>

=== xsf/xeps/xep-0221.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE xep SYSTEM 'xep.dtd' [
  <!ENTITY % ents SYSTEM 'xep.ent'>
%ents;
]>
<?xml-stylesheet type='text/xsl' href='xep.xsl'?>
<xep>
<header>
  <title>Data Forms Media Element</title>
  <abstract>This specification defines an XMPP protocol extension for including media data in XEP-0004 data forms.</abstract>
  &LEGALNOTICE;
  <number>0221</number>
  <status>Draft</status>
  <type>Standards Track</type>
  <sig>Standards</sig>
  <dependencies>
    <spec>XMPP Core</spec>
    <spec>XEP-0004</spec>
  </dependencies>
  <supersedes/>
  <supersededby/>
  <shortname>media-element</shortname>
  <schemaloc>
    <url>http://www.xmpp.org/schemas/media-element.xsd</url>
  </schemaloc>
  &ianpaterson;
  &stpeter;
  <revision>
    <version>1.0</version>
    <date>2008-09-03</date>
    <initials>psa</initials>
    <remark><p>Per a vote of the XMPP Council, advanced status to Draft; concurrently, the XMPP Registrar issued the urn:xmpp:media-element namespace.</p></remark>
  </revision>
  <revision>
    <version>0.6</version>
    <date>2008-08-06</date>
    <initials>psa</initials>
    <remark><p>Further modified examples to track changes to XEP-0231.</p></remark>
  </revision>
  <revision>
    <version>0.5</version>
    <date>2008-08-06</date>
    <initials>psa</initials>
    <remark><p>Modified examples to track changes to XEP-0231.</p></remark>
  </revision>
  <revision>
    <version>0.4</version>
    <date>2008-07-27</date>
    <initials>psa</initials>
    <remark><p>Generalized text regarding inclusion of parameters in type attribute per RFC 2045.</p></remark>
  </revision>
  <revision>
    <version>0.3</version>
    <date>2008-06-18</date>
    <initials>psa</initials>
    <remark><p>Changed MUST to SHOULD regarding inclusion of uri element; allowed inclusion of codecs parameter in type attribute per RFC 4281; added Security Considerations section.</p></remark>
  </revision>
  <revision>
    <version>0.2</version>
    <date>2008-01-30</date>
    <initials>psa</initials>
    <remark><p>Modified to reuse data element from XEP-0231.</p></remark>
  </revision>
  <revision>
    <version>0.1</version>
    <date>2007-07-11</date>
    <initials>psa/ip</initials>
    <remark><p>Initial version, split off from XEP-0158.</p></remark>
  </revision>
</header>

<section1 topic='Introduction' anchor='intro'>
  <p>In certain protocols that make use of &xep0004;, it can be helpful to include media data such as small images. One example of such a "using protocol" is &xep0158;. This document defines a method for including media data in a data form.</p>
</section1>

<section1 topic='Media Element' anchor='media'>
  <p>The root element for media data is &lt;media/&gt;. This element MUST be qualified by the "urn:xmpp:media-element' namespace. The &lt;media/&gt; element MUST be contained within a &lt;field/&gt; element qualified by the 'jabber:x:data' namespace.</p>
  <p>If the media is an image or video then the &lt;media/&gt; element SHOULD include 'height' and 'width' attributes specifying the recommended display size of the media in pixels.</p>
  <p>The &lt;media/&gt; element SHOULD contain at least one &lt;uri/&gt; element to specify the out-of-band location of the media data. <note>Constrained execution environments prevent some clients (e.g., Web clients) from rendering media unless it has been received out-of-band.</note> If included, the &lt;uri/&gt; element MUST contain a URI that indicates the location and MUST include a 'type' attribute that specifies the MIME type of the media. If the URI scheme is cid: then the identifier MUST refer to a bit of binary data as described in &xep0231;.</p>
  <p>The 'type' attribute of the &lt;uri/&gt; element is REQUIRED. The value of the 'type' attribute MUST match the syntax specified in &rfc2045;. That is, the value MUST include a top-level media type, the "/" character, and a subtype; in addition, it MAY include one or more optional parameters (e.g., the "audio/ogg" MIME type in the example shown below includes a "codecs" parameter as specified in &rfc4281;). The "type/subtype" string SHOULD be registered in the &ianamedia;, but MAY be an unregistered or yet-to-be-registered value.</p>
  <example caption='Audio Media Element'><![CDATA[
<media xmlns='urn:xmpp:media-element'>
  <uri type='audio/x-wav'>
    http://victim.example.com/challenges/speech.wav?F3A6292C
  </uri>
  <uri type='audio/ogg; codecs=speex'>
    cid:sha1+a15a505e360702b79c75a5f67773072ed392f52a@bob.xmpp.org
  </uri>
  <uri type='audio/mpeg'>
    http://victim.example.com/challenges/speech.mp3?F3A6292C
  </uri>
</media>
  ]]></example>
  <p>The cid: URI points to data that can be retrieved using the protocol described in &xep0231; and the data element would be included along with the XMPP stanza containing the data form.</p>
  <p>The following example is provided only for the purpose of illustration; consult the specifications for using protocols (e.g., <cite>XEP-0158</cite>) to see canonical examples.</p>
  <example caption='Inclusion in Data Form'><![CDATA[
<x xmlns='jabber:x:data' type='form'>
  [ ... ]
  <field var='ocr'>
    <media xmlns='urn:xmpp:media-element'
           height='80'
           width='290'>
      <uri type='image/jpeg'>
        http://www.victim.com/challenges/ocr.jpeg?F3A6292C
      </uri>
      <uri type='image/jpeg'>
        cid:sha1+f24030b8d91d233bac14777be5ab531ca3b9f102@bob.xmpp.org
      </uri>
    </media>
  </field>
  [ ... ]
</x>
  ]]></example>
</section1>

<section1 topic='Security Considerations' anchor='security'>
  <p>The ability to include arbitrary binary data implies that it is possible to send scripts, applets, images, and executable code, which may be potentially harmful. To reduce the risk of such exposure, an implementation MAY choose to not display or process such data but instead either completely ignore the data, show only the value of the 'alt' attribute (if included), or prompt a human user for approval (either explicitly via user action or implicitly via a list of approved entities from whom the user will accept binary data without per-event approval).</p>
</section1>

<section1 topic='IANA Considerations' anchor='iana'>
  <p>This document requires no interaction with &IANA;.</p>
</section1>

<section1 topic='XMPP Registrar Considerations' anchor='registrar'>
  <section2 topic='Protocol Namespaces' anchor='ns'>
    <p>The &REGISTRAR; includes "urn:xmpp:media-element" in its registry of protocol namespaces (see &NAMESPACES;).</p>
  </section2>
</section1>

<section1 topic='XML Schema' anchor='schema'>
  <code><![CDATA[
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    targetNamespace='urn:xmpp:media-element'
    xmlns='urn:xmpp:media-element'
    elementFormDefault='qualified'>

  <xs:annotation>
    <xs:documentation>
      The protocol documented by this schema is defined in
      XEP-0221: http://www.xmpp.org/extensions/xep-0221.html
    </xs:documentation>
  </xs:annotation>

  <xs:element name='media'>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref='uri' minOccurs='0' maxOccurs='unbounded'/>
      </xs:sequence>
      <xs:attribute name='height' type='xs:unsignedShort' use='optional'/>
      <xs:attribute name='width' type='xs:unsignedShort' use='optional'/>
    </xs:complexType>
  </xs:element>

  <xs:element name='uri'>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base='xs:anyURI'>
          <xs:attribute name='type' type='xs:string' use='required'/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>
  ]]></code>
</section1>

</xep>
